### ISSUE TITLE
No Licensing

### ISSUE THREAD

**Issue by chrisjd20** [MiaLearnsToCode/candy-crush#1]
I didn't see any public licensing for this. You did great work and I was hoping to use this for a FREE cyber security CTF challenge I was working on. I would be modifying this for a different theme but be using your underlying code. This would be window dressing for me to teach players web app vulns (though nothing to do with your own code). 

Would you be ok with me using and modifying your code in my own project and or you add a license of some sort? I'll be sure to link your repo here in my project.

**Comment by MiaLearnsToCode** [comment]
Of course it would be fine! Thanks for checking.

**Comment by chrisjd20** [comment]
Awesome, thanks!
